//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContinousIntegration
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CIEntities : DbContext
    {
        public CIEntities()
            : base("name=CIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Projects> T_Projects { get; set; }
        public DbSet<T_Registrations> T_Registrations { get; set; }
        public DbSet<T_ReleaseMappings> T_ReleaseMappings { get; set; }
        public DbSet<T_Releases> T_Releases { get; set; }
        public DbSet<T_Status> T_Status { get; set; }
        public DbSet<T_Streams> T_Streams { get; set; }
        public DbSet<T_SubReleases> T_SubReleases { get; set; }
        public DbSet<T_Users> T_Users { get; set; }
    }
}
