//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContinousIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Projects
    {
        public T_Projects()
        {
            this.T_Streams = new HashSet<T_Streams>();
        }
    
        public int C_ProjectID { get; set; }
        public string C_ProjectName { get; set; }
        public string C_ProjectDescription { get; set; }
        public System.DateTime C_LastModified { get; set; }
    
        public virtual ICollection<T_Streams> T_Streams { get; set; }
    }
}
