//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContinousIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Releases
    {
        public T_Releases()
        {
            this.T_ReleaseMappings = new HashSet<T_ReleaseMappings>();
            this.T_ReleaseMappings1 = new HashSet<T_ReleaseMappings>();
            this.T_SubReleases = new HashSet<T_SubReleases>();
        }
    
        public int C_ReleaseID { get; set; }
        public int C_StreamID { get; set; }
        public string C_ReleaseName { get; set; }
        public int C_StatusID { get; set; }
        public System.DateTime C_LastModified { get; set; }
    
        public virtual ICollection<T_ReleaseMappings> T_ReleaseMappings { get; set; }
        public virtual ICollection<T_ReleaseMappings> T_ReleaseMappings1 { get; set; }
        public virtual T_Status T_Status { get; set; }
        public virtual T_Streams T_Streams { get; set; }
        public virtual ICollection<T_SubReleases> T_SubReleases { get; set; }
    }
}
