//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContinousIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Registrations
    {
        public int C_RegisterID { get; set; }
        public string C_FirstName { get; set; }
        public string C_LastName { get; set; }
        public string C_EmailID { get; set; }
        public string C_Password { get; set; }
    }
}
