//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContinousIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ReleaseMappings
    {
        public int C_MapID { get; set; }
        public int C_SourceReleaseID { get; set; }
        public int C_InclusiveReleaseID { get; set; }
        public int C_InclusiveSubReleaseID { get; set; }
        public System.DateTime C_LastModified { get; set; }
    
        public virtual T_Releases T_Releases { get; set; }
        public virtual T_Releases T_Releases1 { get; set; }
        public virtual T_SubReleases T_SubReleases { get; set; }
    }
}
