//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContinousIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Registrations
    {
        public T_Registrations()
        {
            this.T_UserProjectMappings = new HashSet<T_UserProjectMappings>();
            this.T_UserRoleMappings = new HashSet<T_UserRoleMappings>();
        }
    
        public int C_RegisterID { get; set; }
        public string C_FirstName { get; set; }
        public string C_LastName { get; set; }
        public string C_EmailID { get; set; }
        public string C_Password { get; set; }
    
        public virtual ICollection<T_UserProjectMappings> T_UserProjectMappings { get; set; }
        public virtual ICollection<T_UserRoleMappings> T_UserRoleMappings { get; set; }
    }
}
