//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContinousIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Roles
    {
        public T_Roles()
        {
            this.T_UserRoleMappings = new HashSet<T_UserRoleMappings>();
        }
    
        public int C_RoleID { get; set; }
        public string C_RoleName { get; set; }
        public System.DateTime C_LastModified { get; set; }
    
        public virtual ICollection<T_UserRoleMappings> T_UserRoleMappings { get; set; }
    }
}
