//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContinousIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Status
    {
        public T_Status()
        {
            this.T_Releases = new HashSet<T_Releases>();
            this.T_SubReleases = new HashSet<T_SubReleases>();
        }
    
        public int C_StatusID { get; set; }
        public string C_StatusName { get; set; }
    
        public virtual ICollection<T_Releases> T_Releases { get; set; }
        public virtual ICollection<T_SubReleases> T_SubReleases { get; set; }
    }
}
