//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContinousIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SubReleases
    {
        public T_SubReleases()
        {
            this.T_ReleaseMappings = new HashSet<T_ReleaseMappings>();
        }
    
        public int C_SubReleaseID { get; set; }
        public int C_ReleaseID { get; set; }
        public string C_SubReleaseName { get; set; }
        public int C_StatusID { get; set; }
        public System.DateTime C_LastModified { get; set; }
    
        public virtual ICollection<T_ReleaseMappings> T_ReleaseMappings { get; set; }
        public virtual T_Releases T_Releases { get; set; }
        public virtual T_Status T_Status { get; set; }
    }
}
