//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContinousIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UserProjectMappings
    {
        public int C_MapID { get; set; }
        public int C_UserID { get; set; }
        public int C_ProjectID { get; set; }
        public System.DateTime C_LastModified { get; set; }
    
        public virtual T_Projects T_Projects { get; set; }
        public virtual T_Users T_Users { get; set; }
    }
}
